export const AUTHETICATION = "AUTHENTICATION";
export const GET_AUTHORS = "GET_AUTHORS";
export const GET_AUTHOR_BOOKS = "GET_AUTHOR_BOOKS"
export const GET_FILTERED_AUTHOR = "GET_FILTERED_AUTHOR"
export const RESET_AUTHOR_FILTER = "RESET_AUTHOR_FILTER"
export const SET_AUTHOR_SEARCH_KEYWORD = "SET_AUTHOR_SEARCH_KEYWORD"
export const GET_FILTERED_BOOKS = "GET_FILTERED_BOOKS"
export const GET_FILTERED_BOOKS_SEARCH = "GET_FILTERED_BOOKS_SEARCH"

export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_FILTER_BOOK_AUTHOR = "GET_FILTER_BOOK_AUTHOR"

export const ADD_NEW_BOOK = "ADD_NEW_BOOK"